---
- hosts: localhost
  gather_facts: yes
  tasks:
    - name: Make sure homebrew bin is in path
      ansible.builtin.lineinfile:
        path: /etc/paths
        state: present
        line: '/opt/homebrew/bin'
      become: true
      become_user: root
      when: "'MacOSX' in ansible_distribution"

    - name: Setup for Ubuntu
      include_tasks: ./ansible/ubuntu.yml
      when: ansible_distribution == 'Ubuntu'

    - name: Universal playbooks
      block: 
        - name: Install Dotfiles
          include_tasks: ./ansible/dotfiles.yml

        # - name: Install Homebrew apps
        #   include_tasks: ./ansible/homebrew.yml

        - name: Install and Setup Oh My ZSH
          include_tasks: ./ansible/zsh.yml

        # - name: Install Utilities
        #   include_tasks: ./ansible/utilities.yml

        - name: Install asdf
          include_tasks: ./ansible/asdf.yml

        - name: Setup and configure pyenv
          include_tasks: ./ansible/pyenv.yml

        - name: Setup and configure kubectl
          include_tasks: ./ansible/kubectl.yml

        - name: Configure VSCode
          include_tasks: ./ansible/vscode.yml
          when: "'MacOSX' in ansible_distribution"

        - name: Configure asdf for IaC
          include_tasks: ./ansible/iac_asdf.yml

