  - name: Install UI Apps
    homebrew_cask:
      pkg: "{{ item }}"
      state: present
      accept_external_apps: yes
    with_items:
      - iterm2
      - google-chrome
      - visual-studio-code
      - sublime-text
      - pgadmin4
    tags:
      - apps
