  - name: (Dotfiles) create dir .vim
    file:
      path: ~/.vim
      state: directory
      recurse: no
  - name: (Dotfiles) create vim swap dir
    file:
      path: ~/.vim/swaps
      state: directory
      recurse: no
      owner: "{{ lookup('env', 'USER') }}"

  - name: (Dotfiles) copy zsh folder
    copy:
      src: zsh/
      dest: "~/.zsh"

  - name: (Dotfiles) create vim backup dir
    file:
      path: ~/.vim/backups
      state: directory
      recurse: no
  - name: (Dotfiles) create dir .config
    file:
      path: ~/.config
      state: directory
      recurse: no
  - name: (Dotfiles) create dir .tmp
    file:
      path: ~/.tmp
      state: directory
      recurse: no
  - name: (Dotfiles) create dir .fonts
    file:
      path: ~/.fonts
      state: directory
      recurse: no
