- name: "Download 'kubectl'"
  shell: |
    curl -LO https://dl.k8s.io/release/v1.23.13/bin/linux/amd64/kubectl

- name: Install 'kubernetes-cli'
  become: true
  become_user: root
  shell: |
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl



