- name: "Install 'pyenv'"
  shell: |
    url https://pyenv.run | bash

- name: Install tested version of python
  shell: |
    pyenv install 3.10.12
    pyenv global 3.10.12

- name: "Reshim Python for asdf"
  shell: |
    source {{ lookup('env', 'HOME') }}/.asdf/asdf.sh
    asdf global python system
    pip3 install ansible
    pip3 install virtualenv
    pip3 install virtualenvwrapper
    asdf reshim python

